# Deploy ipa-jfk tool using parcel

dist: xenial
language: node_js

node_js:
- "15"

jobs:
  include:
    - language: python
      python: 3.8
      script:
      - python -c "print('Hi from Python3!')"

branches:
  only:
  - master

before_install: 
- curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
- source ~/.bashrc
- nvm install v15.14.0
- nvm use v15.14.0

install:
- npm install -g yarn
- yarn

before_script:
- yarn update

script: 
- npm run build

after_script: 
- echo "ipa.citruxonve.net" > dist/CNAME

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  keep_history: true
  on:
    branch: main